build: off

clone_folder: c:\gopath\src\github.com\Bios-Marcel\sampcmd-go

environment:
  GOPATH: c:\gopath

stack: go 1.11

before_test:
  - go get -v ./...
  - go vet ./...

test_script:
  - go test ./...